version: '3.7'
services:
  app:
    depends_on:
      - postgres
    container_name: docker-node-sequelize
    restart: always
    build: .
    ports:
      - '80:3000'
    command:
      "yarn run start"
    links: 
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=levantcarta-store
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=Dummy123
    ports: 
      - "5432:5432"
